### ISSUE TITLE
Python 3.5 requirement?

### ISSUE THREAD

**Issue by a-urth** [tailhook/vagga-box#2]
As for current implementation python>=3.5 is required to run vagga-box due to changes in pathlib.
Same issue was in vagga-docker.
So we can add implicit requirement for python>=3.5 or make same fix as for vagga-docker.
What do You think?

**Comment by tailhook** [comment]
I've added a description in README.rst. What do you mean by "implicit requirement"? Should I add an assertion on `sys.version_info`? If yes, where it should be, in setup.py or in script that is started?

**Comment by a-urth** [comment]
I think readme is enough.
